### PR TITLE
WIP: Simplify and streamline PackageEvaluator

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by IainNZ** [comment]
Pinging @tkelman @staticfloat @timholy @waldyrious @catawbasam @StefanKarpinski as people who take at least some interest in this. Basically, I've simplified everything. Not necessarily as simple as possible, but much simpler. The process is now as follows:

- Package is installed. This is run very simply from the shell, i.e. `julia -e 'Pkg.add...'`. I'd already been doing this since the move to the VM.
- Package is analyzed with `src/preptest.jl`. All this does is see if a `test/runtests.jl` file exists, and if we have any exceptions for this package. If there is no such file, **it doesn't try to find an alternative, or try to just load the package** - it'll just declare "no tests". If it does exist, it'll generate a test running shell script with the timeouts, xvfb, etc.
- Assuming it could be tested, that shell script is launched, which is just `Pkg.test`. This again resolves any possible issues with julia calling julia calling julia... and should help with some weird issues that were sometimes seen that I suspect came from that.
- `src/prepjson.jl` then runs to pull all this together into a per-package test result file.

So we now have only four status: `tests_pass`, `tests_fail`, `no_tests`, `not_possible`, which I think makes things a lot simpler. I've updated pkg.julialang.org for this change, but I haven't pushed it because I want two full daily runs.

I've also gone through the exceptions and re-evaluated them to see if they still made sense. I've also tried to document better why they are there.

With this change we've now got on 0.3:
```
Tests pass: 379 (64%)
Tests fail: 56 (9%)
No tests: 107 (18%)
Package untestable: 53 (9%)
Total: 595
```
and before we had
```
Tests pass: 401 (67%)
Tests fail: 56 (9%)
No tests, package loads: 42 (7%)
Package doesn't load: 37 (6%)
Package untestable	: 60 (10%)
Total: 596
```
I'm not sure why there is one less! But basically the drop for passing tests is from the small number of older packages that didn't upgrade to `test/runtests.jl`, which is very old at this point. Those 22 + the old "no tests loads" and some of the "package doesn't load" make up the new "no tests".

**Comment by staticfloat** [comment]
Cool!  I like the 350+ LOC reduction.  :)

**Comment by IainNZ** [comment]
The next big change is possibly to support v0.3, v0.4, and v0.5 testing simultaneously (this just means changing up the "release"/"nightly" dichotomy). The question is how useful is it to have v0.5 early on - not sure if its that useful.

**Comment by IainNZ** [comment]
@mlubin

**Comment by tkelman** [comment]
> The next big change is possibly to support v0.3, v0.4, and v0.5 testing simultaneously (this just means changing up the "release"/"nightly" dichotomy)

We'll also need to figure out the same issue on Travis.

Looks like a nice improvement overall, will be good to stop giving a free pass to packages that haven't standardized to `test/runtests.jl` yet.

What happens now for a package that fails `using Foo`? If it only runs via `Pkg.test`, then I guess that just counts as failing tests? It's probably not so important to be too clever with this right away, but eventually some method of detecting when a package's dependencies are failing to load causing indirect failure would be useful.

**Comment by IainNZ** [comment]
> What happens now for a package that fails using Foo? If it only runs via Pkg.test, then I guess that just counts as failing tests? It's probably not so important to be too clever with this right away, but eventually some method of detecting when a package's dependencies are failing to load causing indirect failure would be useful.

Theres two possibilities. It either has tests, and fails (fine), or it doesn't have tests, and we now do not catch it. A good and worrying example of this is ICU.jl, which doesn't have tests. It powers Calendar.jl, which does have tests, and most packages that use ICU.jl use it through Calendar.jl. So, its sort of covered?

**Comment by tkelman** [comment]
I guess most package authors know well enough what their dependencies are, and how to distinguish a dependency-induced failure better than a simple automated system could. As long as they or the package's users are paying enough attention to look at the failure in the first place.

> This again resolves any possible issues with julia calling julia calling julia... and should help with some weird issues that were sometimes seen that I suspect came from that.

Should probably put a pin in that as something somebody should revisit down the road to see if it can be isolated and addressed in base, whatever it may have been.

**Pull request merged**
