### PR TITLE
use a do block instead of close, and always add datastructures

### LINKED ISSUE #101: Not creating json files for all tested packages
This is something that happens more often when I run in parallel, on 0.4.0-rc1 and newer. Here's an example output that I killed partway through for nightlyMZ: https://gist.github.com/f9a6595912faa0567616

which resulted in the following files getting output:
```
tkelman@davinci:~/PackageEvaluator.jl/scripts$ ls nightlyMZ
MachineLearning.json  PKGEVAL_MachineLearning_add.log   PKGEVAL_Mamba_test.log
MachineLearning.sh    PKGEVAL_MachineLearning_test.log  PKGEVAL_ManifoldLearning_add.log
MacroTools.sh         PKGEVAL_MachO_add.log             PKGEVAL_ManifoldLearning_test.log
Mamba.json            PKGEVAL_MacroTools_add.log        PKGEVAL_MapLight_add.log
Mamba.sh              PKGEVAL_MacroTools_test.log
ManifoldLearning.sh   PKGEVAL_Mamba_add.log
```

MachineLearning and Mamba and a few later packages (if I let it go for longer) output json files successfully, but MacroTools and most other packages don't. I realize you've got a lot going on right now but I could use help looking into this from anyone who might have any ideas what's happening here.

### PR DESCRIPTION
**Pull request by tkelman**
this might explain the intermittent failure to write json files I've been seeing

~~let me confirm whether this fixes things before you merge this though~~ fixes #101

### CODE REVIEW

**Comment by IainNZ** [comment]
Looks fine, but why would this change things?

**Comment by tkelman** [comment]
Nondeterministic finalizers possibly not getting run before the process closes? Not sure yet, still looking into it.

**Comment by tkelman** [comment]
Alright no this doesn't actually fix anything. The hell.

**Comment by tkelman** [comment]
Adding datastructures fixes matters. Precompilation and optional dependencies don't play together nicely. I'll try to fix a few places in packages where that's breaking but in the meantime this works.

**Comment by IainNZ** [comment]
I always suspected something was amiss with the JSON/DataStructures thing!

**Comment by IainNZ** [comment]
Is this still need with the fixes?

**Comment by tkelman** [comment]
yes the datastructures thing is, people are arguing about const instead of merging a fix to json :(

**Comment by IainNZ** [comment]
Can ditch this later if needed

**Pull request merged**
