### PR TITLE
Add xlrd to setup.sh

### PR DESCRIPTION
**Pull request by davidanthoff**
On travis this actually didn't work and I had to use ``pip install xlrd`` instead, but let's try the python-xlrd package first here, it should do the trick.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@IainNZ Any chance this could get merged? ExcelReaders.jl needs that and I'd love to see the package pass the evaluator! Thanks.

**Comment by IainNZ** [comment]
Sorry, read this but never took any action. Did you test that it worked?

**Comment by davidanthoff** [comment]
I don't have a setup where I could test this. On travis this didn't work, and instead I ended up using ``pip install xlrd``, and that works. Not sure how I could try this out, could you just merge this and see whether this works on the evaluator machine? If it doesn't we could try to replace that line with the pip install. Let me know if you have a better idea...

**Comment by davidanthoff** [comment]
Oh, but I should say that this line did not crash on travis, so I wouldn't expect that this would cause trouble for any other package. But, who knows...

**Comment by IainNZ** [comment]
PackageEvaluator uses Vagrant, should work on any operating system. Please check out the README, ask if you have any questions. You don't need to go through the whole rigamarole though, it'd be sufficient to check it works on an Ubuntu 12.04 machine, which I believe Travis is.

**Comment by davidanthoff** [comment]
@IainNZ I tested some more. I now understand why ``apt-get`` didn't work on travis (long story, not important here).

Essentially there are two options to install xlrd: 

- using ``apt-get``: ``apt-get`` on the precise release is on a very, very old xlrd version that doesn't work, and my understanding is that PackageEvaluator is using precise, correct? On trusty things would work, but that seems like a big change and I would vote against that (unless you plan to change over to trusty for other reasons).
- using ``pip``: That works on travis, so to the extend that I can test that without going through the whole vagrant setup, I did.

I just pushed a commit that uses ``pip`` for this.

**Comment by davidanthoff** [comment]
@IainNZ any thoughts? I think this could just be merged.

**Comment by IainNZ** [comment]
Yeah I'll probably merge this today, been travelling

**Comment by IainNZ** [comment]
OK, fixed, at least when i check it manually.

**Comment by IainNZ** [comment]
And now its correct on the website too

**Comment by davidanthoff** [comment]
Great, thanks a lot!

**Pull request closed without merging**
