### PR TITLE
update R installation, required for RCall

### PR DESCRIPTION
**Pull request by simonbyrne**
Hopefully this should be sufficient to get RCall working.

### CODE REVIEW

**Comment by IainNZ** [comment]
Can you test this?

**Comment by simonbyrne** [comment]
Maybe, but it'll take me a while to look at it.

**Comment by IainNZ** [comment]
Same for me

**Comment by simonbyrne** [comment]
Haha, no worries. I'll try to look into it later this week.

**Comment by simonbyrne** [comment]
I just tried this out: it seemed to work okay.

**Pull request merged**
